name: Blue Jays Transactions Checker

on:
  schedule:
    # Run hourly at minute 15 (e.g., 1:15, 2:15, etc.)
    - cron: '15 * * * *'
  # Also allow manual triggering via GitHub Actions UI
  workflow_dispatch:

jobs:
  check-transactions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz
          
      - name: Run transactions checker
        env:
          # Configure the email password from GitHub secrets
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python bluejays_transactions.py
          
      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add last_check.json last_transactions.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update transaction data [skip ci]" && git push)
